Repository EC-CUBE/ec-cube2, pull requests merged in 2018-08, with the labels that each got.

#202 fix #124 selected 属性の h 修飾子を削除
  data/Smarty/templates/admin/basis/tax.tpl
  data/Smarty/templates/admin/order/mail.tpl
  data/Smarty/templates/admin/products/review.tpl
  data/Smarty/templates/admin/total/index.tpl
  data/Smarty/templates/default/contact/index.tpl
  data/Smarty/templates/default/frontparts/form_personal_input.tpl
  data/Smarty/templates/sphone/contact/index.tpl
  data/Smarty/templates/sphone/shopping/nonmember_input.tpl
Labels: bug:Low

#90 UTF-8依存文字が入力された際にCSVの行が消失するバグのfix
  data/class/helper/SC_Helper_CSV.php
  data/mtb_constants_init.php
  html/install/sql/insert_data.sql
Labels: bug, enhancement

#201 fix #194 ガラケーを無効にする
  data/class/SC_Display.php
Labels: discussion

#211 郵便関係のURL修正 (php7)
  data/Smarty/templates/default/contact/index.tpl
  data/Smarty/templates/default/frontparts/form_personal_input.tpl
  data/Smarty/templates/sphone/contact/index.tpl
  data/Smarty/templates/sphone/frontparts/form_personal_input.tpl
  data/Smarty/templates/sphone/shopping/nonmember_input.tpl
  data/mtb_constants_init.php
  html/install/sql/insert_data.sql
Labels: bug:Middle
