Repository EC-CUBE/ec-cube2, pull requests merged in 2019-04, with the labels that each got.

#247 SQL調整
  html/install/sql/create_table_mysqli.sql
  html/install/sql/create_table_pgsql.sql
Labels: enhancement

#248 会員登録と管理画面ログインのテスト追加
  .travis.yml
  composer.json
  composer.lock
  ctests/_support/MailCatcherGuzzle5.php
  ctests/acceptance.suite.yml
  ctests/acceptance/AdminHomeCept.php
  ctests/acceptance/EntryCept.php
  ctests/acceptance/_bootstrap.php
  eccube_install.sh
Labels: enhancement

#253 事業承継に伴う権利者の名義変更漏れ
  LICENSE.txt
  data/class/pages/upgrade/LC_Page_Upgrade_Download.php
  html/install/templates/agreement.tpl
  templates/templates.xml
Labels: enhancement

#255 Use Docker container to Mailcatcher
  .travis.yml
Labels: enhancement

#252 smartyの後方互換処理の追加
  data/class/SC_View.php
Labels: enhancement

#223 fgetcsvのテストを追加
  data/class/SC_Initial.php
  tests/class/pages/admin/products/LC_Page_Admin_Products_UploadCSVTest.php
  tests/product.csv
Labels: enhancement, ready-for-merge

#251 SC_FormParam のテストケースを追加
  tests/class/SC_FormParamTest.php
Labels: enhancement

#254 SC_Session のテストを追加
  tests/class/SC_SessionTest.php
Labels: enhancement

#260 Fix cache directories
  .travis.yml
Labels: enhancement

#261 Fix issue of EC-CUBE#93 商品一覧の価格順並び替えが登録されていない商品規格に影響される
  data/class/SC_Product.php
  tests/class/SC_Product/SC_Product_findProductIdsOrderTest.php
Labels: bug
