Repository EC-CUBE/ec-cube2, pull requests merged in 2019-11, with the labels that each got.

#319 SC_SelectSql クラスのメソッドコメント修正
  data/class/SC_SelectSql.php
Labels: enhancement

#321 debug_backtrace() を使用している箇所の改善
  .github/workflows/main.yml
  ctests/acceptance/EntryCept.php
  ctests/acceptance/ProductDetailCept.php
  ctests/acceptance/ProductListCept.php
  ctests/acceptance/WelcomeCept.php
  data/class/SC_Display.php
  data/class/SC_FormParam.php
  data/class/SC_Response.php
  data/class/pages/LC_Page.php
  data/class/util/GC_Utils.php
  tests/class/SC_FormParamTest.php
  tests/class/SC_Response/SC_ResponseTest.php
  tests/class/SC_Response/SC_ResponseWithoutModeTest.php
Labels: enhancement

#324 スマホのマイページの購入履歴詳細画面の「今回加算ポイント」の表示を修正
  data/Smarty/templates/sphone/mypage/history.tpl
Labels: bug

#325 削除漏れの拡張クラスファイル(LC_Page_Redirect_Ex)を削除
  data/class_extends/page_extends/LC_Page_Redirect_Ex.php
Labels: bug

#326 派生クラス側を使っていない箇所を修正
  data/class/pages/admin/basis/LC_Page_Admin_Basis_Tax.php
  data/class/pages/admin/products/LC_Page_Admin_Products_ProductRank.php
  data/class/pages/admin/total/LC_Page_Admin_Total.php
  data/class/pages/mypage/LC_Page_Mypage_History.php
  html/install/index.php
  tests/class/SC_DisplayTest.php
  tests/class/SC_UploadFileTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_cleanupSessionTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_clearShipmentItemTempTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_copyFromCustomerTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_copyFromOrderTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_extractShippingTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_getShippingsTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_setShipmentItemTempTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_sfUpdateOrderNameColTest.php
  tests/class/pages/admin/products/LC_Page_Admin_Products_UploadCSVTest.php
Labels: bug

#327 削除漏れの拡張クラスファイル(SC_Cache_Ex)を削除
  data/class_extends/SC_Cache_Ex.php
Labels: bug

#330 jQueryのバージョンアップ
  .eslintrc.json
  data/Smarty/templates/admin/admin_popup_header.tpl
  data/Smarty/templates/admin/login_frame.tpl
  data/Smarty/templates/admin/main_frame.tpl
  data/Smarty/templates/default/popup_header.tpl
  data/Smarty/templates/default/site_frame.tpl
  data/Smarty/templates/sphone/frontparts/bloc/recommend.tpl
  data/Smarty/templates/sphone/popup_header.tpl
  data/Smarty/templates/sphone/products/detail.tpl
  data/Smarty/templates/sphone/site_frame.tpl
  data/eccube.js
  html/js/eccube.js
  html/js/jquery.colorbox/colorbox.css
  html/js/jquery.colorbox/controls.png
  html/js/jquery.colorbox/jquery.colorbox-min.js
  html/js/jquery.colorbox/loading.gif
  html/user_data/packages/sphone/js/jquery.flickslide.js
  package-lock.json
  package.json
  webpack.config.js
  yarn.lock
Labels: enhancement

#332 スマートフォンの商品一覧にて「もっと見る」をクリックした際のソート順が正しくなかったのを修正
  data/Smarty/templates/sphone/products/list.tpl
  data/class/pages/products/LC_Page_Products_List.php
Labels: bug

#333 GitHub Actions のイベントを限定
  .github/workflows/main.yml
Labels: bug

#335 利用されていないシーケンス dtb_csv_no_seq が作成される #334
  html/install/index.php
Labels: bug

#337 improve/php7 のマージ漏れ
  data/class/SC_SendMail.php
  tests/class/SC_SendMailTest.php
Labels: bug

#339 管理画面ログインのバリデーションをインストーラに合わせる
  .github/workflows/main.yml
  .travis.yml
  codeception.yml
  ctests/acceptance.suite.yml
  ctests/acceptance/InstallerCept.php
  ctests/acceptance/_bootstrap.php
  data/class/pages/admin/LC_Page_Admin_Index.php
  html/install/index.php
  html/install/templates/complete.tpl
  html/install/templates/install_frame.tpl
  html/install/templates/step0.tpl
  html/install/templates/step0_1.tpl
  html/install/templates/step1.tpl
  html/install/templates/step2.tpl
  html/install/templates/step3.tpl
  html/install/templates/step4.tpl
Labels: bug:Low

#340 GitHub Actions のキャッシュを追加
  .github/workflows/main.yml
Labels: enhancement

#341 Windows 環境で LoadClassFileChangeTest が動作しなかったのを修正
  .github/workflows/main.yml
  appveyor.yml
  tests/class/plugin/LoadClassFileChangeTest.php
Labels: bug:Low

#344 Apply composer update
  composer.lock
Labels: enhancement

#346 IE11対応で@babel/polyfillを追加
  .babelrc
  data/eccube.js
  html/js/eccube.js
  package.json
  webpack.config.js
  yarn.lock
Labels: bug:Middle
