Repository EC-CUBE/ec-cube2, pull requests merged in 2019-07, with the labels that each got.

#231 #224
  html/install/sql/insert_data.sql
Labels: enhancement

#284 メンバ変数の修飾子を var から public に修正
  data/class/SC_View.php
Labels: enhancement

#286 LC_Page::plugin_activate_flg を非推奨に
  data/class/SC_FormParam.php
  data/class/SC_View.php
  data/class/helper/SC_Helper_Plugin.php
  data/class/pages/LC_Page.php
  data/class/pages/admin/LC_Page_Admin.php
  data/class/pages/error/LC_Page_Error.php
  data/class/pages/error/LC_Page_Error_DispError.php
  data/class/pages/frontparts/bloc/LC_Page_FrontParts_Bloc.php
  data/class/pages/mypage/LC_Page_Mypage_DownLoad.php
  data/class/pages/products/LC_Page_Products_Detail.php
Labels: enhancement

#285 PHP7 での警告を修正
  ctests/acceptance/_bootstrap.php
  data/Smarty/templates/admin/main_frame.tpl
  data/Smarty/templates/admin/order/disp.tpl
  data/Smarty/templates/admin/order/edit.tpl
  data/Smarty/templates/admin/ownersstore/plugin_hookpoint_list.tpl
  data/Smarty/templates/default/header.tpl
  data/Smarty/templates/default/products/detail.tpl
  data/Smarty/templates/default/products/list.tpl
  data/Smarty/templates/mobile/header.tpl
  data/Smarty/templates/mobile/site_frame.tpl
  data/Smarty/templates/mobile/site_main.tpl
  data/Smarty/templates/sphone/header.tpl
  data/Smarty/templates/sphone/products/detail.tpl
  data/Smarty/templates/sphone/products/list.tpl
  data/class/SC_CartSession.php
  data/class/SC_CheckError.php
  data/class/SC_Session.php
  data/class/graph/SC_Graph_Base.php
  data/class/graph/SC_Graph_Pie.php
  data/class/helper/SC_Helper_Purchase.php
  data/class/helper/SC_Helper_Session.php
  data/class/helper/SC_Helper_TaxRule.php
  data/class/pages/admin/total/LC_Page_Admin_Total.php
  data/class/pages/contact/LC_Page_Contact.php
  data/class/pages/products/LC_Page_Products_Detail.php
  data/class/util/SC_Utils.php
  tests/class/SC_CheckError/SC_CheckError_CHECK_DATE3Test.php
  tests/class/SC_CheckError/SC_CheckError_EMAIL_CHAR_CHECKTest.php
  tests/class/SC_UploadFileTest.php
  tests/class/fixtures/FixtureGenerator.php
  tests/class/helper/SC_Helper_DB/SC_Helper_DB_sfCreateBasisDataCacheTest.php
  tests/class/helper/SC_Helper_DB/SC_Helper_DB_sfGetBasisDataCacheTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_cancelOrderTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_completeOrderTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_getShippingsTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_registerOrderCompleteTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_registerOrderTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_rollbackOrderTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_saveOrderTempTest.php
  tests/class/helper/SC_Helper_Purchase/SC_Helper_Purchase_setShipmentItemTempForSoleTest.php
  tests/class/plugin/LoadClassFileChangeTest.php
  tests/class/test/util/Test_Utils.php
Labels: enhancement, ready-for-merge

#294 READMEからwikiのコピーライトポリシーにリンクするように修正
  README.md
Labels: document
