Repository EC-CUBE/ec-cube2, pull requests merged in 2020-05, with the labels that each got.

#278 [fix] refs #100
  data/class/pages/admin/products/LC_Page_Admin_Products_Product.php
Labels: bug, discussion

#280 [fix] refs #101 SC_UploadFile::getFormFileList() 第1,2引数を省略可能とし、基本は省略する
  data/class/SC_UploadFile.php
  data/class/pages/admin/basis/LC_Page_Admin_Basis_PaymentInput.php
  data/class/pages/admin/products/LC_Page_Admin_Products_Product.php
  data/class/pages/products/LC_Page_Products_Detail.php
Labels: discussion, enhancement

#380 refs #111 SC_FormParam::setHtmlDispNameArray() の判定が不適切
  data/class/SC_FormParam.php
Labels: bug:Low

#360 プラグインを任意のディレクトリに配置できるように修正
  data/app_initial.php
  data/class/SC_ClassAutoloader.php
  data/class/helper/SC_Helper_Plugin.php
  data/class/plugin/SC_Plugin_Util.php
  tests/class/fixtures/plugin/FixturePlugin/FixturePlugin.php
  tests/class/fixtures/plugin/FixturePlugin/Fixture_SC_Customer.php
  tests/class/plugin/LoadClassFileChangeCustomDirTest.php
  tests/class/plugin/LoadClassFileChangeTest.php
Labels: discussion, enhancement

#389 2.17系だと2.13系のモジュールをインストールが出来ない問題を強引に解決する
  data/class/pages/upgrade/LC_Page_Upgrade_ProductsList.php
Labels: enhancement
