Repository EC-CUBE/ec-cube2, pull requests merged in 2020-11, with the labels that each got.

#409 検索条件を IN から EXISTS に変更
  data/class/pages/admin/contents/LC_Page_Admin_Contents_RecommendSearch.php
Labels: enhancement

#418 グラフをGoogle Chartを使って描画する
  ctests/acceptance/admin/total/AdminTotalCept.php
  data/Smarty/templates/admin/total/index.tpl
  data/Smarty/templates/admin/total/page_age.tpl
  data/Smarty/templates/admin/total/page_job.tpl
  data/Smarty/templates/admin/total/page_member.tpl
  data/Smarty/templates/admin/total/page_products.tpl
  data/Smarty/templates/admin/total/page_term.tpl
Labels: enhancement

#419 Weekly build
  .github/workflows/deploy.yml
  .github/workflows/main.yml
Labels: enhancement

#420 非推奨のメソッド(SC_Helper_DB_Ex::sfCalcIncTax())を使用しないよう修正
  data/class/SC_Fpdf.php
  data/class/helper/SC_Helper_DB.php
  data/class/pages/rss/LC_Page_Rss_Products.php
Labels: enhancement

#422 SC_Response::sendRedirect() 第2引数のURLエンコード漏れを修正
  data/class/SC_Response.php
Labels: bug

#427 composer update
  composer.lock
Labels: dependencies, enhancement
