Repository EC-CUBE/ec-cube2, pull requests merged in 2025-01, with the labels that each got.

#1117 軽微な誤りを修正
  data/class/helper/SC_Helper_CSV.php
  data/class/pages/admin/total/LC_Page_Admin_Total.php
Labels: bug:Low

#1114 アノテーション追加 SC_Query::$conn
  data/class/SC_Query.php
Labels: enhancement

#1111 SC_FormParam をグローバルでインスタンス化すると E_WARNING が出力されるのを修正
  data/class/SC_FormParam.php
Labels: bug:Low

#1137 スマートフォンテンプレート sfGMOCartDisplay などを削除
  data/Smarty/templates/sphone/cart/index.tpl
  data/Smarty/templates/sphone/mypage/change.tpl
Labels: bug

#1144 SC_Fpdf::setOrderData() Fatal error #1135
  data/class/SC_Fpdf.php
Labels: bug:Low

#1133 switch - case の条件重複を修正
  data/class/api/operations/ItemSearch.php
Labels: bug:Low
